FROM node:16-alpine
ARG APPID
ARG PRIVATEKEY
ARG CLIENTSECRET
ARG CLIENTID
ARG WEBHOOKSECRET
ARG PORT
WORKDIR /usr/app
COPY package.json .
RUN npm install
COPY . .
EXPOSE 4000
CMD ["npm", "run", "start"]
